Building class
gem/oq-platform-building-class pull request #10
Opened 2017-03-06 13:46 UTC by nastasi-oq

Added:
  * user preferences management
  * weak check for quantitative frequencies
  * visual alert (orange vertical bar) for changes not yet saved
Tests are blocked by current broken platform <-> engine interface.
It is companion of <TO-BE-OPENED> oq-platform PR.

2017-03-06 13:49 UTC, lmartins88 approved these changes

2017-03-06 13:58 UTC, pslh requested changes
Some English language suggestions

2017-03-06 13:58 UTC, pslh commented on openquakeplatform_building_class/models.py
> +    publish_info = models.BooleanField(choices=BOOL_CHOICES, help_text=_('''Would you like for your contribution to be acknowledged in future documentation (eg. technical reports, scientific papers i
"Would you like for your contribution" should be "Would you like your contribution" (i.e. no "for")

2017-03-06 13:58 UTC, pslh commented on openquakeplatform_building_class/templates/building-class/building-class-not-auth.html
> +          <p>Thank you for your interest in contributing for the 'Building typology survey' initiative.</p>
"contributing for" should be "contributing to"

2017-03-06 13:58 UTC, pslh commented on openquakeplatform_building_class/templates/building-class/building-class-tutorial.html
> +          <p>To use this tool please follow the instructions on this video.</p>
"instructions on this video" should be "instructions in this video"

2017-03-06 13:58 UTC, pslh commented on openquakeplatform_building_class/templates/building-class/user-settings.html
> +building classes in the world.<br><br>
Remove "in the world" - this is redundant since we already said the inventory is global

2017-03-13 15:05 UTC, ptormene requested changes

2017-03-13 15:05 UTC, ptormene commented on openquakeplatform_building_class/models.py
> +                            help_text=_('name of the responsible person surname, given name,'
I would add `:` after `person`

2017-03-13 15:05 UTC, ptormene commented on openquakeplatform_building_class/templates/building-class/building-class-tutorial.html
> +        <!-- <div id="absoluteSpinner" class="loading">Loading&#8230;</div> -->
Please check if this line can be removed

2017-03-13 15:05 UTC, ptormene commented on openquakeplatform_building_class/templates/building-class/building-class-tutorial.html
> +        console.log(lang);
Please check if this console.log has to be kept or removed

2017-03-13 15:05 UTC, ptormene commented on openquakeplatform_building_class/templates/building-class/building-class-tutorial.html
> +    console.log(userLang);
Same as above

2017-03-13 15:05 UTC, ptormene commented on openquakeplatform_building_class/views.py
> +#def user_settings(request, **kwargs):
Please check if these commented lines are still needed

2017-03-13 15:36 UTC, ptormene approved these changes
LGTM

2017-03-13 15:37 UTC, merged